[Broker]
Hostname = "mqtt.dioty.co"
Port = 1883
Username = "kylek61294@gmail.com"
Password = "1d3337bc"

UpdateTopic = "/kylek61294@gmail.com/home/garage/door/update"
MetadataTopic = "/kylek61294@gmail.com/home/garage/door/metadata"
ControlTopic = "/kylek61294@gmail.com/home/garage/door/control"

[Controller]
Name = "HomeController"
IsController = true
LogLevel = "DEBUG"
Timezone = "PST"

# Note that the pin numbering is based on the board pin numbering scheme
# specified by the wiringPI library
[[Doors]]
Name = "Middle Door"
SensorPin = 11
ControlPin = 12

[[Doors]]
Name = "Left Door"
SensorPin = 13
ControlPin = 16

