[Broker]
Hostname = "localhost"
Port = 1883

UpdateTopic = "home/garage/door/update"
MetadataTopic = "home/garage/door/metadata"
ControlTopic = "home/garage/door/control"

[Controller]
Name = "HomeController"
IsController = true
LogLevel = "INFO"
Timezone = "PST"

# Note that the pin numbering is based on the board pin numbering scheme
# specified by the wiringPI library
[[Doors]]
Name = "Middle Door"
SensorPin = 11
ControlPin = 12

[[Doors]]
Name = "Left Door"
SensorPin = 15
ControlPin = 16

